apiVersion: apps/v1
kind: Deployment
metadata:
  name: precedentia-embedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding
  template:
    metadata:
      labels:
        app: embedding
    spec:
      containers:
      - name: embedding
        image: docker.io/gabguimaraes/precedentia-embedding:9450530
        ports:
        - containerPort: 5001
        env:
        - name: QDRANT_HOST
          value: "qdrant-db"
        - name: QDRANT_PORT
          value: "6333"
        - name: REDIS_HOST
          value: "redis-db-master"
        - name: REDIS_PORT
          value: "6379"
        - name: QDRANT_VECTOR_SIZE
          value: "1536" 
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
